### ISSUE TITLE
Amazon credentials required.

### ISSUE THREAD

**Issue by sid779** [rohitmanglik/video-creator#2]
I'm building the source code on ubuntu 18.04 while it requires secret access key ID.

``<pre>Traceback (most recent call last):
  File &quot;run.py&quot;, line 49, in &lt;module&gt;
    Text = &apos;&lt;speak&gt;&lt;break time=&quot;1s&quot;/&gt;&lt;/speak&gt;&apos;,TextType=&apos;ssml&apos;)
  File &quot;/home/vikramc/anaconda3/lib/python3.7/site-packages/botocore/client.py&quot;, line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File &quot;/home/vikramc/anaconda3/lib/python3.7/site-packages/botocore/client.py&quot;, line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IncompleteSignatureException) when calling the SynthesizeSpeech operation: &apos;ACCESS&apos; not a valid key=value pair (missing equal-sign) in Authorization header: &apos;AWS4-HMAC-SHA256 Credential=YOUR ACCESS KEY/20190505/us-west-2/polly/aws4_request, SignedHeaders=host;x-amz-date, Signature=b53662e44916e935ded4e0b221d0c4c42b086b1f7f9848e38103d9a5ed1627d4&apos;.</pre>``
I would like to know that whether or not I need to use mine as the aws services are under 12-month free access only.

**Comment by rohitmanglik** [comment]
Hi Vikram,

You can use your free tier account for testing purpose.

Regards

**Comment by sid779** [comment]
Sure thanks
